### ISSUE TITLE
RqMultipart.base doesn't close file descriptors

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#512] opened 2016-01-15 16:41 UTC
RqMultipart doesn't close File stream after creating [tempory file](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/rq/RqMultipart.java#L235)

This is causing following error in case of extensive using RqMultipart:

```
java.io.IOException: Too many open files
    at java.io.UnixFileSystem.createFileExclusively(Native Method)
    at java.io.File.createNewFile(File.java:1006)
    at java.io.File.createTempFile(File.java:1989)
    at java.io.File.createTempFile(File.java:2040)
    at org.takes.rq.RqMultipart$Base.make(RqMultipart.java:235)
    at org.takes.rq.RqMultipart$Base.buildRequests(RqMultipart.java:222)
    at org.takes.rq.RqMultipart$Base.(RqMultipart.java:140)
```

I'd also not rely on File.deleteOnExit method (it's strange for server-side applications) - temporary file should be removed right away

**Comment by davvd** [comment] 2016-01-21 11:48
@yegor256 please pay attention to this issue ([par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment] 2016-01-23 04:20
@exper0 looks like a duplicate of https://github.com/yegor256/takes/issues/254 isn't it?

**Closed** 2017-08-14 08:09 UTC
Labels: duplicate, invalid
