### ISSUE TITLE
RqLengthAware and absent Content-Length

### ISSUE THREAD

**Issue by exper0** [yegor256/takes#511] opened 2016-01-15 14:28 UTC
I found that RqLengthAware request doesn't handle situation when there is no Content-Length header in request(this is typical for GET requests since usually there is no body). RqLengthAware  just returns original socket stream that leads to the situation when application wrap original request with RqLengthAware and expects that it does that it offers - aware the length of the body. Simply speaking, it results in application freeze on socket read. Good example is [org.takes.rq.RqPrint.printBody](https://github.com/yegor256/takes/blob/master/src/main/java/org/takes/rq/RqPrint.java#L119) method:

```
    public void printBody(final OutputStream output) throws IOException {
        final InputStream input = new RqLengthAware(this).body();
        //@checkstyle MagicNumberCheck (1 line)
        final byte[] buf = new byte[4096];
        while (true) {
            final int bytes = input.read(buf); // freeze on Request without Content-Length
            if (bytes < 0) {
                break;
            }
            output.write(buf, 0, bytes);
        }
    }
```

Probably it makes sense to make RqLengthAware more intelligent and handle situation when there is no Content-Length. For instance, treat absence of Content-Length as zero (at least for GET requests)

**Comment by HDouss** [comment] 2016-01-17 18:05
@exper0 The issue is already adressed here : #438

**Comment by exper0** [comment] 2016-01-17 18:27
@HDouss thanks, I already found that issue and already implemented #498 that is a blocker for #438

**Comment by HDouss** [comment] 2016-01-17 18:28
@exper0 Thanks. So do you agree that this one is a duplicate of #438 ?

**Comment by exper0** [comment] 2016-01-17 18:32
@HDouss yes. Should I close it?

**Comment by HDouss** [comment] 2016-01-17 18:36
@exper0 I think so.

**Closed** 2016-01-17 18:37 UTC
