### ISSUE TITLE
Build config and encoding test issue

### ISSUE THREAD

**Issue by YamStranger** [yegor256/takes#124] opened 2015-04-04 13:45 UTC
@yegor256 during build, if default java encoding is not specified build fails with message:

Failed tests:
  RsXSLTTest.convertsXmlToHtml:53 default charset during testing must be UTF-8
Expected: "UTF-8"
     but: was "windows-1251"

We can update config to be sure that tests run successfully and nothing is broken.

For this we need to add configuration of maven-surefire-plugin:
This will work correctly:
....
		<plugin>
			  <groupId>org.apache.maven.plugins</groupId>
			  <artifactId>maven-surefire-plugin</artifactId>
			  <version>2.15</version>
			  <configuration>
				<argLine>-Dfile.encoding=UTF-8</argLine>
			  </configuration>
		</plugin>
...

P.S. If charset used in all project (for encoding and decoding character streams) is defined by java configuration, its incorrect, it must be defined during init of framework tools. Reason: server can be run in different encoding (different from UTF-8), and as result - some problems can rise up although test during build are successful. So its new Bug :)

**Comment by yegor256** [comment] 2015-04-04 16:22
@YamStranger it's by design, check "Important" paragraph at the end of Quick Start section, in README.md

**Comment by davvd** [comment] 2015-04-04 16:33
@yegor256 only @YamStranger can close this issue, since he opened it

**Comment by yegor256** [comment] 2015-04-04 16:36
@davvd it's invalid one

**Closed by yegor256** 2015-04-04 16:36 UTC
Labels: duplicate
