### ISSUE TITLE
Remove all 'null' usages in code

### ISSUE THREAD

**Issue by mkordas** [yegor256/takes#555] opened 2016-01-29 17:52 UTC
Takes advertises itself as a library without any `null`. That's not true, I see at least 26 [`null` usages](https://github.com/yegor256/takes/search?l=java&q=null) in Java code.

I'd expect removing `null` from as many places as possible and replacing them with alternatives. 
If some external API actually demands `null` and there's no workaround, we need to admit it in README, and say about few exceptions related to bad external APIs.

I'm fine to solve that issue with PDD approach.

**Comment by davvd** [comment] 2016-01-30 10:07
@mkordas I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment] 2016-01-30 10:07
@mkordas I set milestone here to `1.0`, let me know if it is wrong

**Comment by davvd** [comment] 2016-01-30 10:27
@mkordas thanks for this report, I added 15 mins to your account, in transaction `56ac901105fa01580100020c`

**Comment by davvd** [comment] 2016-02-01 13:30
@happy-neko the task is yours,please go ahead

**Comment by Happy-Neko** [comment] 2016-02-06 17:04
We should make clear what exactly we consider null-free design project-wise. From my point of view:

* Every public API method we expose should not return `null`. Alternatives are throwing exception or returning nullable container if return value is optional (`Optional` in guava / java 8, in takes we have similar `Opt<T>`).
* Do not accept `null` values as method parameters values in out API (up to debate). Alternative approach is to mark parameters with `@NotNull ` / `@Nullable` annotations for self-documentation and static analyser purposes.

Additional consideration:
* We could not stop using 'null' internally because this is how language is designed and core Java library and almost every external library uses it extensively. Workarounds here are pointless.

I have reviewed takes code (except unit tests because they do not expose public API) and found no `null` usages that violates these principles. So it is pretty safe to say that "null-free" is true.

@mkordas what do you think?

**Comment by mkordas** [comment] 2016-02-06 18:17
@Happy-Neko please see http://www.yegor256.com/2014/05/13/why-null-is-bad.html - it states that null is bad  in general, not only in public API

**Comment by Happy-Neko** [comment] 2016-02-06 18:53
@mkordas The problem is we can do nothing if foreign API method can return `null` or accepts it as parameter.

**Comment by mkordas** [comment] 2016-02-07 09:07
@Happy-Neko we can use `Opt` or `Optional` in such cases

**Comment by Happy-Neko** [comment] 2016-02-07 16:07
> we can use Opt or Optional in such cases

@mkordas We still need to test for `Optional` value presence every time we made `null` check before. 
This is hiding the problem under extra layer of code complexity imho.

@yegor256 What do you think?

**Comment by yegor256** [comment] 2016-02-09 04:19
@Happy-Neko I disagree with this:

> We could not stop using null internally because this is how language is designed and core Java library and almost every external library uses it extensively. Workarounds here are pointless.

We can avoid using null everywhere. Let's try to do it. It's a matter of principle :)

**Comment by mkordas** [comment] 2016-02-09 20:46
@Happy-Neko I share the same view as @yegor256 - let's try at least.
Moreover, can you add name tag to your comment https://github.com/yegor256/takes/issues/555#issuecomment-180811432?

**Comment by Happy-Neko** [comment] 2016-02-12 18:11
@yegor256 @mkordas Ok.

**Comment by Happy-Neko** [comment] 2016-02-12 18:11
@davvd We need more time here.

**Comment by Happy-Neko** [comment] 2016-02-12 21:56
@mkordas First step done.

I have implemented `Opt.Nullable` container to store possible-null value returned by library methods (PR #610).

Next puzzles:
* Wrap all library methods that may return `null` in `Opt.Nullable` #608
* `null` value should not be placed in `Opt.Single` container #609

**Comment by davvd** [comment] 2016-02-13 09:12
> @davvd We need more time here.

@happy-neko sure, thanks for telling me, take your time

**Comment by yegor256** [comment] 2017-08-14 08:09
@0crat in

**Comment by 0crat** [comment] 2017-08-14 08:10
> @0crat in ([here](https://github.com/yegor256/takes/issues/555#issuecomment-322125946))

@yegor256 Job `gh:yegor256/takes#555` is in scope.

**Comment by 0crat** [comment] 2017-08-14 22:15
Job `gh:yegor256/takes#555` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment] 2017-11-16 18:56
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment] 2017-11-16 19:17
Oops! Job `gh:yegor256/takes#555` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-11-16 19:18
Oops! Job `gh:yegor256/takes#555` is not assigned to anyone.

**Comment by neonailol** [comment] 2018-01-09 12:11
@yegor256 Please provide more information about the issue.
For example lets look at `org.takes.rq.RqHrefTest#failsOnAbsentRequestLine`

```java
    @Test(expected = HttpException.class)
    public void failsOnAbsentRequestLine() throws IOException {
        new RqHref.Base(
            new RqSimple(Collections.<String>emptyList(), null)
        ).href();
    }
```

Class in scope is `RqSimple`, should it constructor be changed to accepting only `Opt` instances, or add another one with changed arguments.

Next one in this chain is `RqSimple` constructor body

```java
public RqSimple(final Iterable<String> head, final InputStream body) {
        super(
            new Request() {
                @Override
                public Iterable<String> head() {
                    return head;
                }
                @Override
                public InputStream body() {
                    return body;
                }
            }
        );
    }
```

As seen from test, we can pass null to body, so should body method be changed to return `Opt`?

**Comment by 0crat** [comment] 2018-02-02 17:04
The job [#555](https://github.com/yegor256/takes/issues/555) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment] 2018-02-04 14:00
@mkordas there is no public api that can return null in project. Opt.Nullable was rejected in favor of Opt.Empty/Opt.Single and it's already widely used in library, i believe this task can be closed.

**Comment by neonailol** [comment] 2018-02-11 11:38
@yegor256 almost 10 days passed, and no response from the ticket reporter, i think this task can be closed

**Comment by yegor256** [comment] 2018-02-12 16:21
@mkordas @neonailol closing.

**Closed by yegor256** 2018-02-12 16:21 UTC
Labels: 30 mins, @happy-neko, DEV, bug

**Comment by 0crat** [comment] 2018-02-12 16:22
Order was successfully finished: +30 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+555](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment] 2018-02-12 16:31
The job [#555](https://github.com/yegor256/takes/issues/555) is now out of scope
