### ISSUE TITLE
Wrap all methods that may return null in Opt.Nullable

### ISSUE THREAD

**Issue by Happy-Neko** [yegor256/takes#608] opened 2016-02-12 21:34 UTC
All library methods calls that may return `null` should be wrapped in `Opt.Nullable` and checked for value presence with `Opt.has()`.

**Comment by davvd** [comment] 2016-02-16 10:49
@yegor256 please do something about it, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by krzyk** [comment] 2016-03-06 20:45
@Happy-Neko This is a todo, that should be code that introduced `Opt.Nullable`, it is not a bug in master branch.

**Comment by yegor256** [comment] 2017-08-14 08:10
@0crat in

**Comment by 0crat** [comment] 2017-08-14 08:10
> @0crat in ([here](https://github.com/yegor256/takes/issues/608#issuecomment-322126102))

@yegor256 Job `gh:yegor256/takes#608` is in scope.

**Comment by 0crat** [comment] 2017-08-14 22:15
Job `gh:yegor256/takes#608` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment] 2017-11-16 18:59
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment] 2017-11-16 19:17
Oops! Job `gh:yegor256/takes#608` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-11-16 19:18
Oops! Job `gh:yegor256/takes#608` is not assigned to anyone.

**Comment by 0crat** [comment] 2018-01-08 17:11
Job `gh:yegor256/takes#608` assigned to @neonailol  ([profile](http://www.0crat.com/u/neonailol})). The budget is [fixed](http://datum.zerocracy.com/pages/policy.html#4) and it is 30 minutes. Please, read [§4](http://datum.zerocracy.com/pages/policy.html#4), [§8](http://datum.zerocracy.com/pages/policy.html#8), and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment] 2018-01-09 12:12
@yegor256 Please provide more information about the issue.
For example lets look at `org.takes.rq.RqHrefTest#failsOnAbsentRequestLine`

```java
    @Test(expected = HttpException.class)
    public void failsOnAbsentRequestLine() throws IOException {
        new RqHref.Base(
            new RqSimple(Collections.<String>emptyList(), null)
        ).href();
    }
```

Class in scope is `RqSimple`, should it constructor be changed to accepting only `Opt` instances, or add another one with changed arguments.

Next one in this chain is `RqSimple` constructor body

```java
public RqSimple(final Iterable<String> head, final InputStream body) {
        super(
            new Request() {
                @Override
                public Iterable<String> head() {
                    return head;
                }
                @Override
                public InputStream body() {
                    return body;
                }
            }
        );
    }
```

As seen from test, we can pass null to body, so should body method be changed to return `Opt`?

**Comment by neonailol** [comment] 2018-01-10 14:46
@yegor256 there is no public api that can return null in project. `Opt.Nullable` was rejected in favor of `Opt.Empty`/`Opt.Single` and it's already wildly used in library, i believe this task can be closed.

**Comment by yegor256** [comment] 2018-01-10 16:55
@neonailol ask ticket reporter please.

**Comment by neonailol** [comment] 2018-01-10 16:59
@Happy-Neko will you agree with me on this topic?

>  there is no public api that can return null in project. Opt.Nullable was rejected in favor of Opt.Empty/Opt.Single and it's already wildly used in library, i believe this task can be closed.

**Comment by 0crat** [comment] 2018-01-21 05:29
The user @neonailol[/z](https://www.0crat.com/u/neonailol) resigned from [#608](https://github.com/yegor256/takes/issues/608), please stop working

**Comment by 0crat** [comment] 2018-02-12 18:54
The job [#608](https://github.com/yegor256/takes/issues/608) assigned to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/431853426). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Closed** 2018-02-13 10:41 UTC

**Comment by 0crat** [comment] 2018-02-13 10:44
Order was successfully finished: +30 points just awarded to @t-izbassar[/z](https://www.0crat.com/u/t-izbassar), total is [+255](https://www.0crat.com/u/t-izbassar)

**Comment by 0crat** [comment] 2018-02-13 10:51
The job [#608](https://github.com/yegor256/takes/issues/608) is now out of scope
