### ISSUE TITLE
Exception in thread "main" java.io.IOException: empty request

### ISSUE THREAD

**Issue by ezhov-da** [yegor256/takes#740] opened 2017-07-31 12:00 UTC
Hello, i'm use this framework, how write in README.md and catch java.io.IOException with text: "empty request".

This my Stack Trace:

```
Exception in thread "main" java.io.IOException: empty request
	at org.takes.rq.RqLive.parse(RqLive.java:92)
	at org.takes.rq.RqLive.<init>(RqLive.java:56)
	at org.takes.http.BkBasic.accept(BkBasic.java:84)
	at org.takes.http.FtBasic.loop(FtBasic.java:116)
	at org.takes.http.FtBasic.start(FtBasic.java:102)
	at ru.ezhov.junit.TestVelocity.main(TestVelocity.java:33)
```

And class with main method:

```java
public class TestVelocity
{
    private static final Logger LOG = Logger.getLogger(TestVelocity.class.getName());

    public static void main(String[] args) throws Exception
    {
        new FtBasic(
                new TkFork(
                        new FkRegex("/", new TkVelocity()),
                        new FkRegex(
                                "/execute",
                                new TkFork(
                                        new FkMethods("POST,PUT", new TkGroovy())
                                )
                        )
                ),
                10110
        ).start(Exit.NEVER);
    }
}
```

Thanks.

**Comment by 0crat** [comment] 2017-07-31 12:00
@yegor256 please, pay attention to this issue

**Comment by ezhov-da** [comment] 2017-07-31 13:00
Maybe i found, why thows this exception.

I use .html file with Velocity and Bootstrap.
And in file use this tag and href:
`<a class="navbar-brand" href="#">`

I'm click on the link and server throws this exception.

Its can be reason?

Thanks.

**Comment by yegor256** [comment] 2017-07-31 16:22
@ezhov-da I can't reproduce the problem. The code you showed above works fine for me. What version of Takes are you using? Can you show the entire code?

**Comment by ezhov-da** [comment] 2017-07-31 18:08
@yegor256 Yes, i can show the code.
Project source: https://github.com/ezhov-da/java/tree/master/exservice
It's a little project for understending your frameforks.
I'm testing my project home and again have exception.

Thanks for answers.

**Comment by yegor256** [comment] 2017-07-31 18:18
@ezhov-da I checked the repository, it looks correct. How do you test it? What do I have to do to reproduce the bug?

**Comment by ezhov-da** [comment] 2017-07-31 19:17
Sorry, but I can't special  repeat this exception. This very strange.
This absolutly random exception.
I will continue my project and if I can find reason or can special reproduce this bug, necessarily write.
Thanks.

**Comment by leocd277** [comment] 2018-01-24 16:57
Hello @yegor256, I'm seeing this when I use "new RsRedirect("/")", or go back one page, or when redirecting to the Twitter authentication page when in private mode. All of these happen in Firefox. With Chome/Chromium seems to work just fine. I'm using Firefox 58, Chromium 63.0.3239.84 and Takes 1.8.1

**Comment by dgroup** [comment] 2018-01-28 02:05
Hi @yegor256 
I got the same exception during deploy to Heroku
```java
Exception in thread "main" java.io.IOException: empty request
   at org.takes.rq.RqLive.parse(RqLive.java:92)
   at org.takes.rq.RqLive.<init>(RqLive.java:56)
   at org.takes.http.BkBasic.accept(BkBasic.java:84)
   at org.takes.http.FtBasic.loop(FtBasic.java:116)
   at org.takes.http.FtBasic.start(FtBasic.java:102)
   at org.dgroup.badge.milestone.App.main(App.java:62)
Process exited with status 1
```
Takes version is `1.8.1`.
```java
public static void main(final String... args) throws IOException {
        new FtBasic(
            new TkSlf4j(
                new TkFork(
                    new FkIndex(),
                    new FkBadge(args)
                )
            ),
            // @checkstyle MagicNumberCheck (1 line)
            new Port(args, 8080).value()
        ).start(Exit.NEVER);
    }
```
The same codebase works fine on JDK8 alpine and Oracle JDK 9
```cmd
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```
Seems to be environment dependent issue... It fails during each deploy, therefore, it's not a floating issue.

Google Chrome `64.0.3282.119 (Official Build) (64-bit)`
Firefox `57.0.4`

**Comment by 0crat** [comment] 2018-03-06 05:12
Job [#740](https://github.com/yegor256/takes/issues/740) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2018-03-06 05:12
Thanks for your contribution, @ezhov-da[/z](https://www.0crat.com/u/ezhov-da)! If you would be a member of [the project](https://www.0crat.com/p/C3FFK3YAY), you would now earn +15 reputation points, as explained in [§29](http://www.zerocracy.com/policy.html#29). You can join and apply to it, see [§2](http://www.zerocracy.com/policy.html#2).

**Comment by ezhov-da** [comment] 2018-03-06 20:42
Hello, I'm tested my application on version Takes 1.8.6 and exception [Exception in thread "main" java.io.IOException: empty request] not found, application is work.

**Comment by 0crat** [comment] 2018-09-07 10:31
The job [#740](https://github.com/yegor256/takes/issues/740) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2501034032); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2018-09-18 13:50
The job [#740](https://github.com/yegor256/takes/issues/740) assigned to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/2611349056); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by paulodamaso** [comment] 2018-09-19 13:30
@dgroup Is this error still happening to you? I couldn't reproduce it, what I have to do to make this bug happen?

**Comment by paulodamaso** [comment] 2018-09-21 13:27
@ezhov-da Looks like this problem is not happening anymore,please close the issue.

**Comment by 0crat** [comment] 2018-09-23 16:15
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by paulodamaso** [comment] 2018-09-27 02:05
@0crat refuse

**Comment by 0crat** [comment] 2018-09-27 02:42
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/740#issuecomment-424932374))

@paulodamaso The user @paulodamaso[/z](https://www.0crat.com/u/paulodamaso) resigned from [#740](https://github.com/yegor256/takes/issues/740), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-09-27 03:57
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @paulodamaso[/z](https://www.0crat.com/u/paulodamaso)

**Comment by ypshenychka** [comment] 2018-11-12 17:58
@0crat refuse

**Comment by 0crat** [comment] 2018-11-12 17:59
> @0crat refuse ([here](https://github.com/yegor256/takes/issues/740#issuecomment-437973970))

@ypshenychka The user @ypshenychka[/z](https://www.0crat.com/u/ypshenychka) resigned from [#740](https://github.com/yegor256/takes/issues/740), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2018-11-12 18:00
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)

**Comment by paulodamaso** [comment] 2018-11-24 15:36
@victornoel thanks

**Closed by paulodamaso** 2018-11-24 15:36 UTC
Labels: bug, scope

**Comment by 0crat** [comment] 2018-11-24 15:53
@ypshenychka[/z](https://www.0crat.com/u/ypshenychka) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by 0crat** [comment] 2018-11-24 15:53
The job [#740](https://github.com/yegor256/takes/issues/740) is now out of scope

**Comment by ypshenychka** [comment] 2018-11-24 17:36
@victornoel As far as no solution was provided for this issue, I should mark this ticket as 'bad'. Agree?

**Comment by victornoel** [comment] 2018-11-24 17:42
@ypshenychka haha, of course I don't, I'm paid to close tickets. But if you do I will accept without making a fuss ;)

**Comment by ypshenychka** [comment] 2018-11-24 18:46
@victornoel Fair enough :) But rules are rules...

**Comment by ypshenychka** [comment] 2018-11-24 18:46
@0crat quality bad

**Comment by 0crat** [comment] 2018-11-24 18:48
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)

**Comment by 0crat** [comment] 2018-11-24 18:49
Quality review completed: +8 point(s) just awarded to @ypshenychka[/z](https://www.0crat.com/u/ypshenychka)
