### ISSUE TITLE
IOExceptions with bootstrap

### ISSUE THREAD

**Issue by piotrkot** [yegor256/takes#495] opened 2016-01-03 11:15 UTC
Here is a sample project with 2 IOExceptions being reproduced.
https://github.com/piotrkot/takesbug

**Comment by yegor256** [comment] 2016-01-04 12:12
@piotrkot hm... interesting. thanks for reporting!

**Comment by davvd** [comment] 2016-01-04 12:48
@piotrkot this task will get someone's attention soon

**Comment by davvd** [comment] 2016-01-04 12:48
@piotrkot since there is no milestone yet I set it to "1.0"

**Comment by davvd** [comment] 2016-01-14 19:47
@rajithd can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here

The cost of this task is **30 mins** (this is exactly how much will be paid, not less not more), when the task is [done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment] 2016-01-29 20:26
@rajithd check this ["no obligations principle"](http://www.xdsd.org/2014/04/13/no-obligations-principle.html).. This task is on your name for at least 15 days. If you can't close it within the next 48 hours I will have to assign someone else to it. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck

-30 added to your rating, current score is: [-60](http://www.netbout.com/b/36278?open=rating)

**Comment by davvd** [comment] 2016-02-05 09:45
@rajithd the task is overdue, and I have to re-assign it to someone else. Please, stop working with it immediately. In general, we're against overdue tasks, check [this page](http://www.xdsd.org/2014/04/13/no-obligations-principle.html)... -60 added to your rating, current score is: [-180](http://www.netbout.com/b/36278?open=rating)

**Comment by davvd** [comment] 2016-02-28 12:39
@essobedo the task is yours please proceed

**Comment by essobedo** [comment] 2016-02-29 12:02
@piotrkot As workaround you can use _Bug.class.getResource_ instead of _Bug.class.getResourceAsStream_.

**Comment by essobedo** [comment] 2016-02-29 15:58
@davvd here is my [PR](https://github.com/yegor256/takes/pull/630), please find a reviewer, thanks in advance.

**Comment by davvd** [comment] 2016-02-29 18:30
> @davvd here is my [PR](https://github.com/yegor256/takes/pull/630), please find a reviewer, thanks in advance.

@essobedo OK

**Comment by piotrkot** [comment] 2016-02-29 18:42
@essobedo Yes, I know it could work without the stream. IMHO the constructor with inputstream is a mistake.

**Comment by essobedo** [comment] 2016-02-29 18:45
@piotrkot I agree with you it is a mistake, have a look to my PR to see how I fix it without removing the constructors with InputStream.

**Comment by essobedo** [comment] 2016-03-17 19:11
@davvd the PR has been merged, the ticket and the PR are ready to be reviewed by the QA. Thank you in advance.

**Comment by davvd** [comment] 2016-03-21 20:34
@essobedo it's not yours any more, because it took too long, please stop working with it. added -60 to your rating, now it is equal to [+285](http://www.netbout.com/b/36421?open=rating)

**Comment by essobedo** [comment] 2016-03-21 20:52
> @essobedo it's not yours any more, because it took too long, please stop working with it. added -60 to your rating, now it is equal to +285
@davvd @yegor256 are you kidding me? The PR has been merged already, I did my job already, it was stuck because you did not ask the QA to review. Loosing 60 points with still a quota of 2 instead of 5, it is totally unfair, please give me back my points and add me 30 points for the work done

**Comment by essobedo** [comment] 2016-03-21 20:56
@davvd @yegor256 I asked you to ask the QA to review the ticket 4 days ago

**Comment by yegor256** [comment] 2016-03-21 20:59
@essobedo first you have to close the ticket. only after that the QA will jump in. at the moment the problem is still not solved. too early for QA

**Comment by yegor256** [comment] 2016-03-21 21:00
@essobedo keep in mind that merging a PR doesn't mean solving a problem. you may have 4 PRs for one ticket and still the problem won't be solved.

**Comment by essobedo** [comment] 2016-03-21 21:07
@yegor256 what am I supposed to do then if I wait days for other people to do the part of the job? Like here answers, validations and/or QA? I'm sorry but it is really unfair, I worked hard on this one and you know it, I don't believe that I deserve it. Any time I had an answers, I always answered couple hours later even Sundays. If you think that I'm not good enough to work with you, just tell me but please don't punish me when I don't deserve it.

**Comment by yegor256** [comment] 2016-03-21 21:26
@essobedo good intentions are not enough (basically, we don't care much about intentions). Discipline - this is what is more important. All rules are listed here: http://at.teamed.io/policy Read them once again. I'll put this ticket back to you, because you're new to our process. But keep this in mind for the future: we care only about your objective results. A closed ticket is a result. Everything else is just noise.

**Comment by yegor256** [comment] 2016-03-21 21:26
@davvd pls assign @essobedo back here

**Comment by essobedo** [comment] 2016-03-21 21:35
@yegor256 thank you. Another question why do I still have a quota of 2 instead of 5 as described in the policy?

**Comment by essobedo** [comment] 2016-03-21 21:37
@yegor256 here I'm supposed to ask for "more time" then right?

**Comment by essobedo** [comment] 2016-03-21 21:55
@davvd more time

**Comment by davvd** [comment] 2016-03-22 13:00
> @davvd pls assign @essobedo back here

@yegor256 done, @essobedo is assigned to this task, and is already working on it, AFAIK

**Comment by davvd** [comment] 2016-03-22 13:00
> @davvd more time

@essobedo no problem, thanks for letting me know

**Comment by essobedo** [comment] 2016-03-22 13:18
@yegor256 @davvd what about my 60 points lost, can't I get them back ? I'm new to your process as @yegor256 said, let's say that it was my only and last warning so please give them me back.

**Comment by essobedo** [comment] 2016-03-22 23:34
@davvd the ticket is ready to be reviewed by the QA, thank you in advance?
@davvd how many more days do I have when you accept to give "more time" for the task?

**Comment by yegor256** [comment] 2016-03-22 23:58
@essobedo we can't revert bonus back. the ticket is NOT ready to be reviewed by QA. it will be ready, when it's closed. please, read this entire article: http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html

**Comment by piotrkot** [comment] 2016-03-23 07:25
@essobedo I think now it is the time to ask the one who opened the ticket (that is me) to close it.
Just checked the current version of takes (1.0-SNAPSHOT) with my [takesbug](https://github.com/piotrkot/takesbug). The bug is fixed. Thank you very much for your support.

**Closed** 2016-03-23 07:25 UTC
Labels: 30 mins, @essobedo, bug, DEV

**Comment by essobedo** [comment] 2016-03-23 08:38
@piotrkot you are right, thank you very much

**Comment by essobedo** [comment] 2016-03-23 08:49
@davvd The ticket is closed so it is ready for the QA

**Comment by davvd** [comment] 2016-03-23 18:54
> @davvd The ticket is closed so it is ready for the QA

@essobedo OK

**Comment by davvd** [comment] 2016-03-24 09:41
@ypshenychka please, review this ticket for compliance with our [QA rules](http://at.teamed.io/qa.html)

**Comment by ypshenychka** [comment] 2016-03-24 09:55
@davvd Quality is good.

**Comment by davvd** [comment] 2016-03-24 12:08
> @davvd Quality is good.

@ypshenychka thanks a lot :)

**Comment by davvd** [comment] 2016-03-24 12:15
@essobedo paied 10 mins to @ypshenychka for QA review (payment ID is `81340165`). Thank you, I have added **1 hour** to your account in payment/transaction "`81340181`", time consumed: 20 hours and 7 mins. there is a bonus for fast delivery (m=1207). +60 to your rating, your total score is [+345](http://www.netbout.com/b/36421?open=rating)

**Comment by essobedo** [comment] 2016-03-25 11:47
@davvd many thanks

**Comment by davvd** [comment] 2016-03-25 14:35
> @davvd many thanks

@essobedo np :)
