### ISSUE TITLE
RsWithStatus() with no body can cause IOException.

### ISSUE THREAD

**Issue by alxn** [yegor256/takes#379] opened 2015-08-28 18:03 UTC
I was trying to use the following in a `TkFork` on a `PUT`:

```java
new TkRegex() {
    @Override
    public Response act(final RqRegex req) {
        return new RsWithStatus(
            HttpURLConnection.HTTP_OK
        );
    }
}
```
But when I ran it in a live system I saw:

```java
Caused by: java.io.IOException: Failed PUT request to http://localhost:6001/path
       at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:127)
       at com.jcabi.http.request.BaseRequest.fetchResponse(BaseRequest.java:297)
       at com.jcabi.http.request.BaseRequest.fetch(BaseRequest.java:212)
       ... 20 more
Caused by: java.net.SocketException: Connection reset
       at java.net.SocketInputStream.read(SocketInputStream.java:196)
       at java.net.SocketInputStream.read(SocketInputStream.java:122)
       at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
       at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
       at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
       at java.io.FilterInputStream.read(FilterInputStream.java:133)
       at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3066)
       at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3060)
       at com.jcabi.http.request.JdkRequest$1.body(JdkRequest.java:192)
       at com.jcabi.http.request.JdkRequest$1.send(JdkRequest.java:119)
       ... 22 more
```

That was odd.. since I saw the request-response go through with `ngrep`.

Changing the code to:

```java
new TkRegex() {
   @Override
   public Response act(final RqRegex req) {
       return new RsWithStatus(
           new RsText("hello"),
           HttpURLConnection.HTTP_OK
       );
   }
}
```

Made it work without exception, but obviously it should work without a
body.

**Comment by alxn** [comment] 2015-08-28 18:04
@yegor256 fyi submitted.

**Comment by davvd** [comment] 2015-08-30 20:12
@alxn I am aware of the task, give me some time to find a developer...

**Comment by davvd** [comment] 2015-08-30 20:12
@alxn attached this issue to milestone "1.0" (let me know if this is wrong)

**Comment by davvd** [comment] 2015-08-30 20:18
@mstzn36 the task is yours, the budget is **30 mins**, please go ahead

**Comment by mstzn36** [comment] 2015-08-31 20:56
@alxn can you provide me full of code block if you have? Thank you.

**Comment by alxn** [comment] 2015-08-31 21:08
@mstzn36 I or (@yegor256) could reproduce with a little test I think.

**Comment by mstzn36** [comment] 2015-09-02 20:33
@alxn I ran server with the following code and made PUT request to the server through Postman and did not get any exception? What am I doing wrong? 
<pre>
 new FtBasic(new TkFork(
            new FkRegex("/test", new TkRegex() {
                @Override
                public Response act(final RqRegex request) throws IOException {
                    return new RsWithStatus(HttpURLConnection.HTTP_OK);
                }
            })
        ), 8080).start(Exit.NEVER);
</pre>

**Comment by davvd** [comment] 2015-09-08 19:01
@dimonn12 can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here; Task's budget is **30 mins** (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by dimonn12** [comment] 2015-09-12 16:58
@alxn @davvd I wasn't able to reproduce this issue. Could you provide more details how to reproduce it?

**Comment by dimonn12** [comment] 2015-09-14 12:32
@davvd Sorry, I can't reproduce and fix this issue. Please, assign anybody else for this task.

**Comment by davvd** [comment] 2015-09-23 20:37
@dimonn12 you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck; -30 added to your rating, current score is: [-60](http://www.netbout.com/b/35589?open=rating)

**Comment by davvd** [comment] 2015-09-29 09:32
@dimonn12 it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. added -60 to your rating, now it is equal to [-180](http://www.netbout.com/b/35589?open=rating)

**Comment by davvd** [comment] 2015-11-01 14:40
@bdragan the task is yours, please go ahead

**Comment by bdragan** [comment] 2015-11-01 16:28
@alxn This issue cannot be reproduced any longer. Please close it, or provide more details on how to reproduce it. Thank you!

**Closed** 2015-11-02 20:00 UTC
Labels: 30 mins, @bdragan, bug, DEV

**Comment by davvd** [comment] 2015-11-04 11:42
@ypshenychka review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by ypshenychka** [comment] 2015-11-05 06:22
@bdragan Since you as a ticket performer didn’t prove in a pull request that the problem is not reprocible, the quality of this ticket is bad. Consider this situation for future and create a pull request with a proof - then it will be a good quality ticket.

**Comment by ypshenychka** [comment] 2015-11-05 06:23
@davvd Quality is bad here.

**Comment by davvd** [comment] 2015-11-05 09:08
> @davvd Quality is bad here.

@ypshenychka thanks, we'll try harder next time

**Comment by davvd** [comment] 2015-11-05 09:14
@bdragan added 10 mins to @ypshenychka, for QA review, payment code is `69007433`

**Comment by bdragan** [comment] 2015-11-05 15:47
@ypshenychka Noted, thanks for the remark.
