### ISSUE TITLE
outputStream in org.takes.rs.RsPrint.printBody(OutputStream) never closes

### ISSUE THREAD

**Issue by simonjenga** [yegor256/takes#444] opened 2015-11-19 18:27 UTC

**Comment by davvd** [comment] 2015-11-23 09:34
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment] 2015-11-28 19:11
@simonjenga this is by design, we should not close it, since we don't open it. It's not ours.

**Closed by yegor256** 2015-11-28 19:11 UTC
