### ISSUE TITLE
Add a Response implementation that applies "modifying" Xembly directives

### ISSUE THREAD

**Issue by HDouss** [yegor256/takes#462] opened 2015-12-12 00:14 UTC
Right now, there is an implementation of Response that creates an XML from Xembly directives that build an XML from scratch.
Let's have an implementation that applies "modifying" Xembly directives to an existing XML document. That latter XML document could also be built from Xembly directives.

**Comment by davvd** [comment] 2015-12-15 10:51
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment] 2015-12-17 21:30
@HDouss good idea, but I would rather add a new constructor to existing `RsXembly`:

```
new RsXembly(dirs, document);
```

@HDouss make sense?

**Comment by HDouss** [comment] 2015-12-17 21:37
@yegor256 Yes !

**Comment by davvd** [comment] 2015-12-18 10:53
@hdouss I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment] 2015-12-18 11:01
@hdouss thanks for this report, I added 15 mins to your account, in transaction `72453029`

**Comment by davvd** [comment] 2015-12-21 16:43
@happy-neko could you please pick this up? This [article](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) explains how we work. Any technical questions you may ask right here. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment] 2016-01-05 17:14
@happy-neko you're working with this issue for 15 days already

-30 added to your rating, at the moment it is: [+98](http://www.netbout.com/b/36136?open=rating)

**Comment by davvd** [comment] 2016-01-10 18:22
@happy-neko this task is taking too long, I have to change the performer, sorry. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle... -60 added to your rating, current score is: [-22](http://www.netbout.com/b/36136?open=rating)

**Comment by Happy-Neko** [comment] 2016-01-10 18:46
@davvd PR was merged 3 days ago. What exactly do you want me to do?

**Comment by yegor256** [comment] 2016-01-10 20:53
@Happy-Neko keep in mind that your result is not a PR, but a closed ticket, see http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html You may have a dozen of closed/merged pull requests, but the ticket will stay open, until its author closes it.

**Comment by Happy-Neko** [comment] 2016-01-10 21:53
@yegor256 ok.
@HDouss please review this ticket and close it if problem is solved.

**Comment by HDouss** [comment] 2016-01-10 22:30
@Happy-Neko Thanks !

**Comment by HDouss** [comment] 2016-01-10 22:31
@davvd PR is merged an accepted. Can I close the issue ? Or are you assigning another developer ?

**Comment by davvd** [comment] 2016-01-11 13:21
> @davvd PR is merged an accepted. Can I close the issue ? Or are you assigning another developer ?

@hdouss legally, this ticket is not yours any more, since you ran out of time. let's ask @yegor256 to take a look

**Comment by HDouss** [comment] 2016-01-11 13:24
@davvd I am the author of the issue, not the one who resolved it. Since the PR was accepted, I am asking if I can close the issue, or if you will assign another performer.

**Comment by yegor256** [comment] 2016-01-11 13:28
@HDouss close the issue, if it's fixed

**Closed** 2016-01-11 13:29 UTC
Labels: 30 mins, bug, DEV
