### ISSUE TITLE
 BkParallelTest.requestsAreParallel is not stable

### ISSUE THREAD

**Issue by ekondrashev** [yegor256/takes#333] opened 2015-06-05 19:38 UTC
Please see http://www.rultor.com/t/3957-109363038

```
Results :

Failed tests: 
  BkParallelTest.requestsAreParallel:127 
Expected: <0L>
     but: was <1L>

Tests run: 226, Failures: 1, Errors: 0, Skipped: 4
```

There was already a try to fix it at #309

**Comment by davvd** [comment] 2015-06-06 09:16
@ekondrashev I will find a developer for the task soon...

**Comment by davvd** [comment] 2015-06-06 09:17
@ekondrashev there is no milestone yet, so I set it to `1.0`

**Comment by davvd** [comment] 2015-06-06 09:25
@ekondrashev thanks for the report, I topped your acc for 15 mins, payment ID `58668953`

**Comment by davvd** [comment] 2015-06-06 10:03
@mbarbieri it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket

**30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by davvd** [comment] 2015-06-21 10:08
@mbarbieri you're working with this issue for 15 days already

-30 added to your rating, current score is: [+113](http://www.netbout.com/b/35357?open=rating)

**Comment by mbarbieri** [comment] 2015-06-22 20:42
@davvd I tried several things but with no success... I give up on this... please reassign this to someone else. Thanks

**Comment by davvd** [comment] 2015-06-23 10:29
> @davvd I tried several things but with no success... I give up on this... please reassign this to someone else. Thanks

@mbarbieri -30 points to your rating :(

**Comment by davvd** [comment] 2015-06-23 10:29
> @davvd I tried several things but with no success... I give up on this... please reassign this to someone else. Thanks

@mbarbieri no problem, I will try to find somebody else

**Comment by davvd** [comment] 2015-06-24 12:35
@erimerturk the task is yours please proceed

**Comment by erimerturk** [comment] 2015-06-28 08:36
@yegor256 do you have any suggestion how can i reproduce problem and where should i concentrate for solution ?

**Comment by yegor256** [comment] 2015-06-29 04:16
@erimerturk honestly, no idea... but I believe it's not difficult, just requires some research

**Comment by erimerturk** [comment] 2015-07-05 08:07
@davvd  i have an preterm baby yesterday, please reassign my issue someone else, thank you

**Comment by davvd** [comment] 2015-07-05 09:50
> @davvd  i have an preterm baby yesterday, please reassign my issue someone else, thank you

@erimerturk 30 points deducted from your rating

**Comment by davvd** [comment] 2015-07-05 09:50
> @davvd  i have an preterm baby yesterday, please reassign my issue someone else, thank you

@erimerturk right, I will find someone else, no problem

**Comment by davvd** [comment] 2015-07-11 10:56
@bilalyasar can you please help? Keep in mind [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). If you have any technical questions, don't hesitate to ask right here... The budget of this task is **30 mins**. This is exactly how much time will be compensated, when the task is completed. Read about our [Definition of Done](http://www.xdsd.org/2014/04/15/definition-of-done.html)

**Comment by davvd** [comment] 2015-07-26 11:38
@bilalyasar you're working with this ticket for the last 15 days. If it is not closed within the next 48 hours, it will be re-assigned to someone else, see [No Obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. [This article](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html) should help if you're stuck... added -30 to your rating, now it is equal to [-30](http://www.netbout.com/b/35406?open=rating)

**Comment by davvd** [comment] 2015-07-31 11:12
@bilalyasar it takes too long. Usually, we expect any task to be finished in less than a week. I'll assign someone else. Please stop working with it right now. See our [no obligations](http://www.xdsd.org/2014/04/13/no-obligations-principle.html) principle. -60 added to your rating, current score is: [-90](http://www.netbout.com/b/35406?open=rating)

**Comment by davvd** [comment] 2015-08-17 10:22
@adko-pl this task is for you, keep [these principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) in mind, and don't hesitate to ask any technical questions

The budget of this issue is **30 mins**, which is exactly how much will be paid when the task is *done* (see [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for explanation)

**Comment by yegor256** [comment] 2017-08-14 08:05
@0crat in

**Comment by 0crat** [comment] 2017-08-14 08:05
> @0crat in ([here](https://github.com/yegor256/takes/issues/333#issuecomment-322125039))

@yegor256 Job `gh:yegor256/takes#333` is in scope.

**Comment by 0crat** [comment] 2017-08-14 22:15
Job `gh:yegor256/takes#333` assigned to @caarlos0, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment] 2017-11-14 16:53
@caarlos0 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment] 2017-11-16 19:16
Oops! Job `gh:yegor256/takes#333` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-11-16 19:17
Oops! Job `gh:yegor256/takes#333` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-11-16 19:18
Oops! Job `gh:yegor256/takes#333` is not assigned to anyone.

**Comment by 0crat** [comment] 2018-01-23 01:34
The job [#333](https://github.com/yegor256/takes/issues/333) assigned to @neonailol[/z](https://www.0crat.com/u/neonailol). The budget is 30 minutes, see [§4](http://datum.zerocracy.com/pages/policy.html#4). Please, read [§8](http://datum.zerocracy.com/pages/policy.html#8) and [§9](http://datum.zerocracy.com/pages/policy.html#9). If the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html).

**Comment by neonailol** [comment] 2018-01-24 12:33
@yegor256 i believe this is no longer an issues
run test for 50000 times, and not a single failure was spotted, here is [surefire report](https://github.com/yegor256/takes/files/1659806/surefire-reports.zip)

**Comment by neonailol** [comment] 2018-01-24 12:38
also run it with multiple threads like this `mvn -Dtest=BkParallelTest clean test -T50`
no failures was detected [report](https://github.com/yegor256/takes/files/1659816/surefire-reports.zip)

**Comment by yegor256** [comment] 2018-01-24 14:33
@neonailol ask ticket reporter to close it

**Comment by neonailol** [comment] 2018-01-24 15:32
@ekondrashev issue is no more, see above 3 comments

**Comment by neonailol** [comment] 2018-01-29 03:45
@0crat waiting

**Comment by 0crat** [comment] 2018-01-29 03:45
> @0crat waiting ([here](https://github.com/yegor256/takes/issues/333#issuecomment-361132761))

@neonailol The impediment for [#333](https://github.com/yegor256/takes/issues/333) was registered successfully by @neonailol[/z](https://www.0crat.com/u/neonailol)

**Comment by neonailol** [comment] 2018-01-31 12:24
@yegor256 no response from reporter, and this test are not failing anymore, i suggest to close this ticket

**Comment by yegor256** [comment] 2018-01-31 15:53
@neonailol closing, thanks

**Closed by yegor256** 2018-01-31 15:53 UTC
Labels: 30 mins, @adko-pl, DEV, bug

**Comment by 0crat** [comment] 2018-01-31 15:55
Order was successfully finished: +30 points just awarded to @neonailol[/z](https://www.0crat.com/u/neonailol), total is [+300](https://www.0crat.com/u/neonailol)

**Comment by 0crat** [comment] 2018-01-31 16:03
The job [#333](https://github.com/yegor256/takes/issues/333) is now out of scope
