### ISSUE TITLE
"get \" produces StackOverflowError

### ISSUE THREAD

**Issue by rusefillc** [yegor256/takes#1058] opened 2020-07-25 06:10 UTC
Below shell snippet hopefully tells the complete story

```telnet localhost 8001
Trying 127.0.0.1...
Connected to localhost.localdomain.
Escape character is '^]'.
get \

HTTP/1.1 500 Internal Server Error
Content-Length: 50287
Content-Type: text/plain

java.lang.StackOverflowError
        at java.base/java.lang.Exception.<init>(Exception.java:66)
        at java.base/java.net.URISyntaxException.<init>(URISyntaxException.java:62)
        at java.base/java.net.URI$Parser.fail(URI.java:2913)
        at java.base/java.net.URI$Parser.parseAuthority(URI.java:3247)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158)
        at java.base/java.net.URI$Parser.parse(URI.java:3114)
        at java.base/java.net.URI.<init>(URI.java:600)
        at org.takes.misc.Href.createUri(Href.java:301)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
        at org.takes.misc.Href.createUri(Href.java:313)
```

**Comment by paulodamaso** [comment] 2020-07-26 19:37
@0crat in

**Comment by rusefillc** [comment] 2020-08-15 00:58
@paulodamaso poke?
@yegor256 is not this a pretty serious issue?

**Comment by yegor256** [comment] 2020-08-17 04:43
@rusefillc it seems it is. @paulodamaso what do you think?

**Comment by paulodamaso** [comment] 2020-08-27 19:00
@yegor256 Yeah, we should definitely investigate. I put it on scope (https://github.com/yegor256/takes/issues/1058#issuecomment-664031120) but looks like @0crat did not assigned it to anyone yet

**Comment by 0crat** [comment] 2020-08-27 19:00
Are you speaking to me or about me [here](https://github.com/yegor256/takes/issues/1058#issuecomment-682134058); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by paulodamaso** [comment] 2020-09-02 18:32
@0crat assign @fabriciofx

**Comment by 0crat** [comment] 2020-09-02 18:33
> @0crat assign @fabriciofx  ([here](https://github.com/yegor256/takes/issues/1058#issuecomment-685921031))

@paulodamaso The job [#1058](https://github.com/yegor256/takes/issues/1058) assigned to @fabriciofx[/z](https://www.0crat.com/u/fabriciofx), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/52e812cd-e7cb-464a-8366-1ce986114958); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by fabriciofx** [comment] 2020-09-03 00:44
@rusefillc Can you say the steps/code to reproduce this bug?

**Comment by rusefillc** [comment] 2020-09-03 00:48
@fabriciofx 
telnet localhost 80
get \
<enter>
<enter>

**Comment by fabriciofx** [comment] 2020-09-03 01:07
@rusefillc right, which code has been used to run in back-end?

**Comment by rusefillc** [comment] 2020-09-03 01:11
some version of https://github.com/rusefi/rusefi/blob/master/java_tools/proxy_server/src/main/java/com/rusefi/server/Backend.java#L106

**Comment by fabriciofx** [comment] 2020-09-03 01:16
@rusefillc ok, thanks!

**Comment by fabriciofx** [comment] 2020-09-11 04:43
@rusefillc if you think this issue was fixed, can you close it, please?

**Comment by rusefillc** [comment] 2020-09-11 07:56
@fabriciofx I am sorry I am not noticing any relevant changes. I see https://github.com/yegor256/takes/pull/1065/files which seems to be a relevant test not a relevant fix. Is there a fix somewhere in your opinion? can you please point me at it?

**Comment by fabriciofx** [comment] 2020-09-11 10:23
@rusefillc ah, sorry! My bad! This issue wasn't fixed it. Just has been added a test to reproduce this issue. Sorry about that!

**Comment by paulodamaso** [comment] 2020-09-19 13:55
@rusefillc You can close this one, as @fabriciofx already solved it creating the test, and left a puzzle (https://github.com/yegor256/takes/issues/1068) to continue working on it

**Closed** 2020-09-19 14:09 UTC
Labels: 0crat/role/DEV, 0crat/scope

**Comment by 0crat** [comment] 2020-09-19 14:26
Job `gh:yegor256/takes#1058` is not assigned, can't get performer

**Comment by 0pdd** [comment] 2025-08-08 11:23
@rusefillc the only puzzle [#1068](https://github.com/yegor256/takes/issues/1068) is solved here.
