### ISSUE TITLE
RqLive must pay attention to Content-Length header.

### ISSUE THREAD

**Issue by xupyprmv** [yegor256/takes#486] opened 2015-12-26 16:12 UTC
Current version of `RqLive`  doesn't pay attention to `Content-Length` header, but it has to. For keep-alive connections after `Content-Length` bytes there can be second request (third request and so on, https://en.wikipedia.org/wiki/HTTP_persistent_connection).

If there is no `Content-length` header, then `RqLive` must throw exception.

**Comment by davvd** [comment] 2015-12-31 19:22
@yegor256 please dispatch this issue

**Comment by yegor256** [comment] 2016-01-04 16:58
@xupyprmv I'm not sure I understand the purpose of this... maybe we need something like `RqValidated`, which will validate the encapsulated request before use:

```java
new RqValidated(
  original_request,
  new RqValidated.Check[] {
    new RqValidated.Check() {
      @Override
      public void check(Request req) {
        if (!new RqHeaders.Smart(req).has("Content-Length")) {
          throw new IOException("Content-Length is absent");
        }
      }
    } 
  }
)
```

Did I understand your idea right?

**Comment by xupyprmv** [comment] 2016-01-04 17:06
@yegor256 not only validation. Current version of `RqLive` ignores `Content-Length`. So it reads `InputStream` until end, but after `Content-Length` bytes, there can be second request. So `RqLive`  cannot be used to keep-alive connections.

**Comment by yegor256** [comment] 2016-01-04 20:01
@xupyprmv so, `RqLive` has a bug, right? it doesn't pay attention to `Content-Length`, but it has to. is it what you're complaining about?

**Comment by xupyprmv** [comment] 2016-01-04 20:32
@yegor256 Yes, if we want to use RqLive for keep-alive connections we must pay attention to `Content-Length` header.

**Comment by yegor256** [comment] 2016-01-05 14:34
@xupyprmv can you please update ticket description?

**Comment by xupyprmv** [comment] 2016-01-05 14:43
@yegor256 I updated ticket title and description.

**Comment by yegor256** [comment] 2016-01-06 11:21
@xupyprmv thanks, good bug

**Comment by davvd** [comment] 2016-01-06 12:25
@xupyprmv I added milestone `1.0` to this issue, let me know if there has to be something else

**Comment by davvd** [comment] 2016-01-06 12:40
@xupyprmv thank you for reporting this, I added 15 mins to your acc, transaction `AP-9KY705262R3862154`

**Comment by HDouss** [comment] 2016-01-06 21:31
@yegor256 I don't agree with this. `RqLive` is our basic request implementation. Requests does not have always to specify Content-Length. Typically, GET requests without a body message (which is the most case) don't precise a Content-Length header. Besides, a request could have a chunked message as described [here](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3) : 
>The presence of a message-body in a request is signaled by the inclusion of a Content-Length or Transfer-Encoding header field in the request's message-headers.

Morover, I don't think this issue blocks #456. In #456, we should just get rid of `BkReuse` and move the tests to `BkBasic`.

**Comment by xupyprmv** [comment] 2016-01-07 06:35
@HDouss Ok, we can ignore Content-Length header for GET requests. But we need form not only one `Request` from InputStream. Because stream can contain many requests.

If you move `BkReuse` tests to `BkBasic` you will face with the same problem:

``` Java
    @Test
    public void handlesTwoRequestInOneConnection() throws Exception {
        final String text = "Hello world!";
        final Socket socket = Mockito.mock(Socket.class);
        InputStream stream = new ByteArrayInputStream(
            Joiner.on("\r\n").join(
                "GET / HTTP/1.1",
                "Host:localhost",
                "Content-Length: 2",
                "",
                "hi",
                "GET / HTTP/1.1",
                "Host:localhost",
                "Content-Length: 4",
                "",
                "hihi"
            ).getBytes()
        );
        Mockito.when(socket.getInputStream()).thenReturn(
            stream
        );
        Mockito.when(socket.getLocalAddress()).thenReturn(
            InetAddress.getLocalHost()
        );
        Mockito.when(socket.getLocalPort()).thenReturn(0);
        Mockito.when(socket.getInetAddress()).thenReturn(
            InetAddress.getLocalHost()
        );
        Mockito.when(socket.getPort()).thenReturn(0);
        final ByteArrayOutputStream baos = new ByteArrayOutputStream();
        Mockito.when(socket.getOutputStream()).thenReturn(baos);
        new BkBasic(new TkText("Hello world!")).accept(socket);
        MatcherAssert.assertThat(
                baos.toString(),
                RegexMatchers.containsPattern(text + ".*?" + text)
        );
    }
```

`BkBasic` will maintain input as one request. But It must maintain two requests and return two responses.

**Comment by HDouss** [comment] 2016-01-07 07:56
@xupyprmv It is not about GET requests in particular. We should not consider a request invalid (throw an exception) just because it does not precise a Content-Length header. We should do the following instead : if a request does not precise a Content-Length or a Transfer-Encoding, it should be considered as bodyless. Nothing more than that. For more insight you can see : #438 , #463 and #498.
For #456, BkBasic will maintain input **not** as one request,but as one connection. In #456, you should not make these tests pass. These tests are buggy and should be rewritten anyway (#454). All you have to do is to get rid of the BkReuse class and move the tests to the BKBasic one. You should remember that the issue should take you no more than 30 min.

**Comment by xupyprmv** [comment] 2016-01-07 08:09
@HDouss I understand your position. But why do we need to move buggy tests? They will not pass anyway (because they are buggy, not the code they test).

**Comment by xupyprmv** [comment] 2016-01-07 08:35
@HDouss How about changing this bug description to:

Current version of `RqLive` doesn't pay attention to [message length](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4), but it has to. For keep-alive connections input stream can contain [several request](https://en.wikipedia.org/wiki/HTTP_persistent_connection).

**Comment by HDouss** [comment] 2016-01-07 08:36
@xupyprmv We should move them because they somehow describe requirements. It is good to keep them. Please note that these test are `@Ignore`d for now, so they won't be executed anyway.

**Comment by HDouss** [comment] 2016-01-07 08:42
@xupyprmv The link you provided states clearly that not every request should have content-length, but only : 
> When a message-body is included

Besides, it clearly states that chunked messages (without Content-Length header) are took into account (2nd point) priorily to Content-Length header (3rd point).

And that exactly what I was trying to say by : 
> Requests does not have always to specify Content-Length. Typically, GET requests without a body message (which is the most case) don't precise a Content-Length header. Besides, a request could have a chunked message as described

**Comment by xupyprmv** [comment] 2016-01-07 08:46
@HDouss Yes.  But it doesn't mean that we must ignore message length. It can be zero, it can be specified by Content-Length, but it must properly maintained by `RqLive`. Am I right?

**Comment by HDouss** [comment] 2016-01-07 08:53
@xupyprmv 
>@HDouss How about changing this bug description to:
Current version of RqLive doesn't pay attention to message length, but it has to. For keep-alive connections input stream can contain several requests.

This already a feature of `RqLengthAware` and transitively of `RqPrint` and `RqGeedy`. I think `RqLive` should stay as it is.

**Comment by HDouss** [comment] 2016-01-07 08:56
@xupyprmv 
>@HDouss Yes. But it doesn't mean that we must ignore message length. It can be zero, it can be specified by Content-Length, but it must properly maintained by RqLive. Am I right?

Whenever we have to, we have just to wrap `RqLive` inside `RqLengthAware`, `RqGreedy` or `RqLengthAware`. May be it will be part of the work that have to be done in #418.

**Comment by xupyprmv** [comment] 2016-01-07 09:31
@HDouss Ok. But when we switch from `RqLive` to `RqLengthAware` we will face with the same problem:
> Requests does not have always to specify Content-Length. Typically, GET requests without a body message (which is the most case) don't precise a Content-Length header. 

So `RqLengthAware` must return empty stream instead of body for "zero message length" request:

```Java
     private static InputStream cap(final Request req) throws IOException {
        final Iterator<String> hdr = new RqHeaders.Base(req)
            .header("Content-Length").iterator();
        InputStream body = req.body();
        if (hdr.hasNext()) {
            body = new CapInputStream(body, Long.parseLong(hdr.next()));
        }
        return body; <-- BUG HERE
    }
```
Otherwise we cannot use stream to process second request.

**Comment by HDouss** [comment] 2016-01-07 09:39
@xupyprmv This is exactly the issue stated in #438 (even if it is described differently). The bug is in `RqLengthAware`.

**Comment by xupyprmv** [comment] 2016-01-07 17:25
@HDouss

> This is exactly the issue stated in #438 (even if it is described differently). The bug is in RqLengthAware.

I don't agree with this. #438 about a bug with empty body. But in this ticket, I speak about keep-alive connection (with several requests in InputStream). Sure we can leave `RqLive` as is. But we still need `Request` wrapper that will correctly process keep-alive connections: `RqLive`, `RqLengthAware` or may be new wrapper.

**Comment by HDouss** [comment] 2016-01-07 17:31
@xupyprmv When I said : 
> @xupyprmv This is exactly the issue stated in #438 (even if it is described differently). The bug is in RqLengthAware.

I was not commenting the issue, but was commenting : 
> So RqLengthAware must return empty stream instead of body for "zero message length" request

Please keep the issues separated. Processing keep-alive connection is not the purpose of #456. This issue should not block #456.

**Comment by xupyprmv** [comment] 2016-01-07 17:53
@HDouss I see next line inside issue description:

> implement persistent connections inside BkBasic

Is that comment related to current issue?

**Comment by xupyprmv** [comment] 2016-01-07 19:37
@yegor256 The main idea of this issue was to have a `Request` that can correctly work with keep-alive connections. After discussion with @HDouss , I want to change issue description to:

> `RqLengthAware` must return empty stream instead of [body](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.3) for "zero [message length](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4)" request: 
```Java
     private static InputStream cap(final Request req) throws IOException {
        final Iterator<String> hdr = new RqHeaders.Base(req)
            .header("Content-Length").iterator();
        InputStream body = req.body();
        if (hdr.hasNext()) {
            body = new CapInputStream(body, Long.parseLong(hdr.next()));
        }
        return body; <-- BUG HERE
    }
```
Otherwise we cannot use stream to process second request.

What do you think about that?

**Comment by davvd** [comment] 2016-01-12 12:48
@happy-neko the task is yours, please go ahead

**Comment by Happy-Neko** [comment] 2016-01-12 16:53
@xupyprmv Ticket description and following discussion is confusing.
Please confirm final specifications of this issue:

* What class should be modified.
* What is expected behaviour and how it is different from current situation.

**Comment by xupyprmv** [comment] 2016-01-12 17:20
@Happy-Neko  I think @yegor256, as architect, have to clarify this ticket.

@yegor256 Is current ticket description is valid (according to `takes` architecture) and must be implemented as is? After discussion with @HDouss I think that we must use `RqLengthAware` class to work with keep-alive connections.

**Comment by HDouss** [comment] 2016-01-12 17:24
@xupyprmv IMHO, the issue is not about keep-alive connection in particular. It is about properly reading a request body message in general. And if it is done here, it will be a duplicate of #438 because the resolution will be the same.

**Comment by yegor256** [comment] 2016-01-14 03:03
@xupyprmv as @HDouss pointed already, let's try to keep issues/problems separately. Moreover, keep in mind that we won't help you solve problems of other tickets in this ticket. We will resolve the problem you specify here and only this problem. Whether it will help you solve other problems in other tickets - is not our concern here. Having this in mind, can you explain again what is wrong right now with `RqLive`? Looks like current ticket description is wrong and `RqLive` must **not** throw an exception if `Content-Length` is absent.

**Comment by xupyprmv** [comment] 2016-01-14 04:46
@Happy-Neko This ticket is invalid. There is already class `RqLengthAware` that pays attention to Content-Length header. Nothing to do here.

**Comment by yegor256** [comment] 2016-01-14 05:27
@xupyprmv just close it please

**Closed** 2016-01-14 06:10 UTC
Labels: 30 mins, @happy-neko, bug, DEV, invalid
