### ISSUE TITLE
TkHTML is not tested

### ISSUE THREAD

**Issue by yegor256** [yegor256/takes#50] opened 2015-03-12 06:30 UTC
There is no unit test for `TkHTML` class, let's create one.

**Comment by davvd** [comment] 2015-03-12 10:34
@yegor256 sure, thanks, I added bug tag to it

**Comment by davvd** [comment] 2015-03-12 19:26
@yegor256 thank you for the ticket reported, I topped your account for 15 mins, transaction `000-5aab798d`

**Comment by davvd** [comment] 2015-03-15 16:48
@mgovorischev it's yours now, please proceed keeping in mind [our principles](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html). Feel free to ask any technical questions right here in the ticket. **30 mins** is the budget of the task. This is exactly how much will be paid when the problem is [solved](http://www.xdsd.org/2014/04/15/definition-of-done.html) (no matter how much time you will actually spend). See [this](http://www.xdsd.org/2014/04/17/how-xdsd-is-different.html) for more information

**Comment by mgovorischev** [comment] 2015-03-15 18:13
Given there will be static analysis applied to the changeset before merging it, can I get the codestyle( e.g. checkstyle profile ), requirements for the code to comply with so I could test the compliance before submitting a pull request?

**Comment by yegor256** [comment] 2015-03-15 19:00
@mgovorischev just run `mvn clean install -Pqulice` and you will get all static analysis complains

**Comment by mgovorischev** [comment] 2015-03-22 09:57
After pulling latest changes from upstream it turned out that TkHTMLTest had been already added by @yegor256, so this ticket should probably be reassigned to him and I need a new one

**Comment by yegor256** [comment] 2015-03-22 15:38
@davvd assign this to me pls

**Comment by davvd** [comment] 2015-03-22 17:08
> @davvd assign this to me pls

@yegor256 OK, the task is yours, go ahead

**Closed** 2015-09-27 02:50 UTC
Labels: 30 mins, @yegor256, bug, DEV

**Comment by davvd** [comment] 2015-09-28 10:23
@elenavolokhova review this ticket please, for compliance with our [quality rules](http://www.teamed.io/qa.html)

**Comment by elenavolokhova** [comment] 2015-09-28 17:08
@yegor256 
 According to our [quality rules](http://www.teamed.io/qa.html):
 >Problem reporter and problem solver are two different persons.
 
 This was not a case in this ticket. Please avoid fixing your own issues.
 
  According to our [quality rules](http://www.teamed.io/qa.html):
 > Some of ticket messages must mention all pull requests where the problem was actually fixed.
 
 There is no link to related PR in comments. Please fix this issue and follow this rule in your tickets in the future.

**Comment by yegor256** [comment] 2015-09-28 17:17
@elenavolokhova the test was added in bbe8d21c2a2f7d07e51b2e2e1f6f5bf3be6337a3

**Comment by yegor256** [comment] 2015-09-28 17:17
@elenavolokhova I agree, this should have been done in a pull request, my bad

**Comment by elenavolokhova** [comment] 2015-09-29 05:07
@davvd Quality is acceptable here.

**Comment by davvd** [comment] 2015-09-29 09:26
> @davvd Quality is acceptable here.

@elenavolokhova thanks for the QA review, we'll work better next time

**Comment by davvd** [comment] 2015-09-29 09:32
@yegor256 I added 10 mins to @elenavolokhova (for QA review) in transaction 66242956... **30 mins** added to your account (payment number `000-c7f75751`), many thanks for your contribution! 4528 hours and 41 mins spent here.... +30 added to your rating, current score is: [+13743](http://www.netbout.com/b/35008?open=rating)
