### ISSUE TITLE
Utf8InputStreamReader/Utf8OutputStreamWriter have wrong names

### ISSUE THREAD

**Issue by Iprogrammerr** [yegor256/takes#904] opened 2018-12-18 19:11 UTC
Proper object name should say what object is representing, not what it [does]( https://www.yegor256.com/2015/03/09/objects-end-with-er.html). These two classes need refactoring.

**Comment by 0crat** [comment] 2018-12-18 19:13
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment] 2018-12-18 19:13
@iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3FFK3YAY) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment] 2019-01-17 17:01
Job [#904](https://github.com/yegor256/takes/issues/904) is now in scope, role is `DEV`

**Comment by 0crat** [comment] 2019-01-17 17:14
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @iprogrammerr[/z](https://www.0crat.com/u/iprogrammerr)

**Comment by 0crat** [comment] 2019-02-21 17:43
The job [#904](https://github.com/yegor256/takes/issues/904) assigned to @serranya[/z](https://www.0crat.com/u/serranya), here is [why](https://www.0crat.com/footprint/C3FFK3YAY/4c75055c-f079-4572-8800-590efc5b9509); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Serranya** [comment] 2019-02-22 07:55
@Iprogrammerr So what is your suggestion? How shold the classes be named in your opinion?

@paulodamaso My suggestion is to keep the klasses as they are. They implement the `InputStreamReader`/`OutputStreamWriter` interfaces from the jdk. I think in this case it's reasonable to follow the namingscheme that's already given and that we can't change.

**Comment by Serranya** [comment] 2019-02-28 06:55
@0crat wait for feedback on https://github.com/yegor256/takes/issues/904#issuecomment-466307495

**Comment by 0crat** [comment] 2019-02-28 06:58
> @0crat wait for feedback on https://github.com/yegor256/takes/issues/904#issuecomment-466307495 ([here](https://github.com/yegor256/takes/issues/904#issuecomment-468159711))

@Serranya The impediment for [#904](https://github.com/yegor256/takes/issues/904) was registered successfully by @serranya[/z](https://www.0crat.com/u/serranya)

**Comment by Iprogrammerr** [comment] 2019-03-04 21:14
@Serranya How about changing both reader and writer to content? Then both of these classes are representing content of Utf8Streams. First of them is readable and second writable.

**Comment by Serranya** [comment] 2019-03-06 07:48
@Iprogrammerr Im not sure what you are trying to suggest. Something like
`ReadableUtf8Content` and `WritableUtf8Content`?

**Comment by Iprogrammerr** [comment] 2019-03-06 14:42
@Serranya How about Utf8InputStreamContent and Utf8OutputStreamContent?

**Comment by Serranya** [comment] 2019-03-07 07:17
@Iprogrammerr sure. I can do that.

**Comment by Serranya** [comment] 2019-03-07 11:57
@0crat wait for review of #972

**Comment by 0crat** [comment] 2019-03-07 11:58
> @0crat wait for review of #972  ([here](https://github.com/yegor256/takes/issues/904#issuecomment-470498748))

@Serranya Job [#904](https://github.com/yegor256/takes/issues/904) is already on hold

**Comment by Serranya** [comment] 2019-04-17 15:58
@Iprogrammerr #972 is merged now. Please close this issue if the problem is addressed to your satisfaction.

**Comment by Serranya** [comment] 2019-04-23 09:09
@Iprogrammerr ping

**Comment by sereshqua** [comment] 2020-02-13 17:34
@paulodamaso this can be closed :)

**Comment by paulodamaso** [comment] 2020-02-13 17:40
@sereshqua Thanks you

**Closed by paulodamaso** 2020-02-13 17:40 UTC
Labels: bug, scope, waiting

**Comment by 0crat** [comment] 2020-02-13 18:13
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @serranya[/z](https://www.0crat.com/u/serranya), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment] 2020-02-13 18:15
@0crat quality good

**Comment by 0crat** [comment] 2020-02-13 19:59
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)

**Comment by 0crat** [comment] 2020-02-13 20:09
Order was finished, quality is "good": +35 point(s) just awarded to @serranya[/z](https://www.0crat.com/u/serranya)
